### ISSUE TITLE
Translations not loaded anymore

### ISSUE THREAD

**Issue by stefonarch** [redtide/sddm-conf#8]
Realized just now: localisation is broken now, not sure when it happened, in  the installation of some weeks ago it works.

**Comment by redtide** [comment]
Sorry, I'm not much of help in this context (no Weblate experience)

**Comment by stefonarch** [comment]
I compiled both, master and the removal  branch, saw  no diff. We did this before in LXQt when settings were migrated in other tabs or panels.
I didn't pay attention when testing the saving some days ago, but probably it was in english then too.
@tsujan any idea?

**Comment by redtide** [comment]
Bah, sorry, I got it wrong as it was a problem on loading the translations on Weblate (as it happened initially also with picom-conf), you mean that they are not loaded in the app... though ATM I have some difficult to check there anyway

**Comment by tsujan** [comment]
> @tsujan any idea?

Will look into it tomorrow if the cause isn't found until then.

**Comment by stefonarch** [comment]
It's not possible to go back as it was force-pushed, but also the very first commit now has this issue.

**Comment by tsujan** [comment]
> It's not possible to go back 

We won't need to go back to know why translations don't work. I'm a little busy now but will check the code soon.

**Comment by tsujan** [comment]
The fix: https://github.com/redtide/sddm-conf/pull/10
